In [3]:
# ============================================================
# CREDRESOLVE — COLLECTIONS RECOVERY ANALYTICS
# 04 — ASSIGNMENT FORENSIC ANALYSIS
# ============================================================

from pathlib import Path
import pandas as pd
import numpy as np

# ------------------------------------------------------------
# 1. PATHS
# ------------------------------------------------------------

PROJECT_ROOT = Path.cwd().parent
RAW_DIR = PROJECT_ROOT / "data" / "raw"
OUTPUT_DIR = PROJECT_ROOT / "outputs" / "tables"

OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

print("=" * 90)
print("CREDRESOLVE — ASSIGNMENT FORENSIC ANALYSIS")
print("=" * 90)


# ------------------------------------------------------------
# 2. LOAD RAW DATA
# ------------------------------------------------------------

csv_files = sorted(RAW_DIR.glob("*.csv"))

datasets = {
    file.stem: pd.read_csv(file)
    for file in csv_files
}

print(f"Datasets loaded: {len(datasets)}")


# ============================================================
# A. DUPLICATE PAYMENT FORENSICS
# ============================================================

print("\n" + "=" * 90)
print("A. DUPLICATE PAYMENT FORENSICS")
print("=" * 90)

payments = datasets["payments"].copy()

payments["event_at_parsed"] = pd.to_datetime(
    payments["event_at"],
    errors="coerce"
)

# A1. Duplicate payment IDs
payment_id_profile = (
    payments
    .groupby("payment_id")
    .agg(
        occurrences=("payment_id", "size"),
        accounts=("account_id", "nunique"),
        borrowers=("borrower_id", "nunique"),
        references=("payment_reference", "nunique"),
        amounts=("amount", "nunique"),
        providers=("provider_id", "nunique")
    )
    .reset_index()
)

duplicate_payment_ids = payment_id_profile[
    payment_id_profile["occurrences"] > 1
].copy()

print("Duplicate payment IDs:", len(duplicate_payment_ids))

display(duplicate_payment_ids.head(50))

duplicate_payment_ids.to_csv(
    OUTPUT_DIR / "forensic_payment_id_duplicates.csv",
    index=False
)


# A2. Duplicate payment references
reference_profile = (
    payments
    .dropna(subset=["payment_reference"])
    .groupby("payment_reference")
    .agg(
        occurrences=("payment_reference", "size"),
        payment_ids=("payment_id", "nunique"),
        accounts=("account_id", "nunique"),
        amounts=("amount", "nunique"),
        providers=("provider_id", "nunique")
    )
    .reset_index()
)

duplicate_references = reference_profile[
    reference_profile["occurrences"] > 1
].copy()

print(
    "Duplicate payment references:",
    len(duplicate_references)
)

display(duplicate_references.head(50))

duplicate_references.to_csv(
    OUTPUT_DIR / "forensic_payment_reference_duplicates.csv",
    index=False
)


# A3. Same account + amount + timestamp
payment_event_duplicates = (
    payments
    .dropna(
        subset=[
            "account_id",
            "amount",
            "event_at_parsed"
        ]
    )
    .groupby(
        [
            "account_id",
            "amount",
            "event_at_parsed"
        ]
    )
    .size()
    .reset_index(name="occurrences")
)

payment_event_duplicates = (
    payment_event_duplicates[
        payment_event_duplicates["occurrences"] > 1
    ]
    .sort_values("occurrences", ascending=False)
)

print(
    "Same account + amount + timestamp groups:",
    len(payment_event_duplicates)
)

display(payment_event_duplicates.head(50))

payment_event_duplicates.to_csv(
    OUTPUT_DIR / "forensic_payment_event_duplicates.csv",
    index=False
)


# ============================================================
# B. ATTRIBUTION FORENSICS
# ============================================================

print("\n" + "=" * 90)
print("B. ATTRIBUTION FORENSICS")
print("=" * 90)

calls = datasets["calls"].copy()

calls["event_at_parsed"] = pd.to_datetime(
    calls["event_at"],
    errors="coerce"
)

accounts = datasets["accounts"].copy()


# B1. Payment borrower/account consistency

account_borrower_map = (
    accounts[
        [
            "account_id",
            "borrower_id"
        ]
    ]
    .drop_duplicates("account_id")
    .rename(
        columns={
            "borrower_id": "account_borrower_id"
        }
    )
)

payment_account_check = payments.merge(
    account_borrower_map,
    on="account_id",
    how="left"
)

payment_account_check[
    "borrower_mismatch"
] = (
    payment_account_check["borrower_id"]
    !=
    payment_account_check["account_borrower_id"]
)

borrower_mismatch = payment_account_check[
    payment_account_check["borrower_mismatch"]
    &
    payment_account_check["account_borrower_id"].notna()
].copy()

print(
    "Payment borrower/account mismatches:",
    len(borrower_mismatch)
)

display(borrower_mismatch.head(50))

borrower_mismatch.to_csv(
    OUTPUT_DIR / "forensic_payment_borrower_mismatch.csv",
    index=False
)


# B2. Call borrower/account consistency

call_account_check = calls.merge(
    account_borrower_map,
    on="account_id",
    how="left"
)

call_account_check[
    "borrower_mismatch"
] = (
    call_account_check["borrower_id"]
    !=
    call_account_check["account_borrower_id"]
)

call_borrower_mismatch = call_account_check[
    call_account_check["borrower_mismatch"]
    &
    call_account_check["account_borrower_id"].notna()
].copy()

print(
    "Call borrower/account mismatches:",
    len(call_borrower_mismatch)
)

display(call_borrower_mismatch.head(50))

call_borrower_mismatch.to_csv(
    OUTPUT_DIR / "forensic_call_borrower_mismatch.csv",
    index=False
)


# B3. Payment → prior call attribution signal
# This is an attribution SIGNAL, not proof of causality.

payments_match = payments[
    [
        "payment_id",
        "account_id",
        "event_at_parsed",
        "amount",
        "payment_status"
    ]
].dropna(
    subset=[
        "account_id",
        "event_at_parsed"
    ]
).sort_values("event_at_parsed")

calls_match = calls[
    [
        "call_id",
        "account_id",
        "event_at_parsed",
        "agent_id",
        "campaign_id",
        "vendor_id",
        "call_status"
    ]
].dropna(
    subset=[
        "account_id",
        "event_at_parsed"
    ]
).rename(
    columns={
        "event_at_parsed": "call_event_at"
    }
).sort_values("call_event_at")

attribution_signal = pd.merge_asof(
    payments_match.sort_values("event_at_parsed"),
    calls_match.sort_values("call_event_at"),
    left_on="event_at_parsed",
    right_on="call_event_at",
    by="account_id",
    direction="backward"
)

attribution_signal["hours_since_prior_call"] = (
    attribution_signal["event_at_parsed"]
    -
    attribution_signal["call_event_at"]
).dt.total_seconds() / 3600

print(
    "Payment-to-prior-call attribution records:",
    len(attribution_signal)
)

display(attribution_signal.head(50))

attribution_signal.to_csv(
    OUTPUT_DIR / "forensic_payment_call_attribution.csv",
    index=False
)


# ============================================================
# C. TIMEZONE FORENSICS
# ============================================================

print("\n" + "=" * 90)
print("C. TIMEZONE FORENSICS")
print("=" * 90)

# C1. Profile all actual timezone fields

timezone_profiles = []

for table, column in [
    ("calls", "timezone"),
    ("accounts", "timezone"),
    ("agent_sessions", "timezone"),
    ("vendor_telephony", "timezone")
]:

    df = datasets[table]

    profile = (
        df[column]
        .value_counts(dropna=False)
        .rename_axis(column)
        .reset_index(name="records")
    )

    profile["dataset"] = table

    timezone_profiles.append(profile)

timezone_profile_df = pd.concat(
    timezone_profiles,
    ignore_index=True
)

display(timezone_profile_df)

timezone_profile_df.to_csv(
    OUTPUT_DIR / "forensic_timezone_profile.csv",
    index=False
)


# C2. Correct comparison:
# Call timezone vs ACCOUNT timezone.
#
# Vendor timezone is NOT treated as the expected customer/call
# timezone because vendor timezone represents the vendor system.

account_timezone_map = (
    accounts[
        [
            "account_id",
            "timezone"
        ]
    ]
    .drop_duplicates("account_id")
    .rename(
        columns={
            "timezone": "account_timezone"
        }
    )
)

call_timezone_check = calls.merge(
    account_timezone_map,
    on="account_id",
    how="left"
)

call_timezone_check[
    "account_timezone_difference_flag"
] = (
    call_timezone_check["timezone"]
    !=
    call_timezone_check["account_timezone"]
)

call_timezone_check[
    "account_timezone_difference_flag"
] = (
    call_timezone_check[
        "account_timezone_difference_flag"
    ]
    &
    call_timezone_check["timezone"].notna()
    &
    call_timezone_check["account_timezone"].notna()
)

timezone_differences = call_timezone_check[
    call_timezone_check[
        "account_timezone_difference_flag"
    ]
].copy()

print(
    "Call/account timezone differences:",
    len(timezone_differences)
)

display(timezone_differences.head(50))

timezone_differences.to_csv(
    OUTPUT_DIR / "forensic_call_account_timezone_difference.csv",
    index=False
)


# C3. Calling-hour distribution

calling_hour_profile = (
    calls["event_at_parsed"]
    .dt.hour
    .value_counts()
    .sort_index()
    .rename_axis("hour")
    .reset_index(name="call_count")
)

display(calling_hour_profile)

calling_hour_profile.to_csv(
    OUTPUT_DIR / "forensic_calling_hours.csv",
    index=False
)


# ============================================================
# D. VENDOR MAPPING / VERSION FORENSICS
# ============================================================

print("\n" + "=" * 90)
print("D. VENDOR MAPPING / VERSION FORENSICS")
print("=" * 90)

vendor = datasets["vendor_telephony"].copy()

vendor_profile = (
    vendor[
        [
            "vendor_id",
            "vendor_name",
            "vendor_account_id",
            "timezone",
            "status",
            "schema_version"
        ]
    ]
    .drop_duplicates()
)

display(vendor_profile)

vendor_profile.to_csv(
    OUTPUT_DIR / "forensic_vendor_master_profile.csv",
    index=False
)


# D2. Calls by vendor and schema version

calls_vendor = calls.merge(
    vendor[
        [
            "vendor_id",
            "schema_version"
        ]
    ],
    on="vendor_id",
    how="left"
)

calls_vendor["month"] = (
    calls_vendor["event_at_parsed"]
    .dt.to_period("M")
    .astype(str)
)

vendor_monthly_profile = (
    calls_vendor
    .groupby(
        [
            "month",
            "vendor_id",
            "schema_version"
        ],
        dropna=False
    )
    .size()
    .reset_index(name="call_count")
)

display(vendor_monthly_profile)

vendor_monthly_profile.to_csv(
    OUTPUT_DIR / "forensic_vendor_monthly_profile.csv",
    index=False
)


# D3. Disposition version profile

dispositions = datasets["call_dispositions"].copy()

dispositions["event_at_parsed"] = pd.to_datetime(
    dispositions["event_at"],
    errors="coerce"
)

dispositions["month"] = (
    dispositions["event_at_parsed"]
    .dt.to_period("M")
    .astype(str)
)

disposition_version_profile = (
    dispositions
    .groupby(
        [
            "month",
            "disposition_version",
            "disposition_code"
        ],
        dropna=False
    )
    .size()
    .reset_index(name="records")
)

display(disposition_version_profile)

disposition_version_profile.to_csv(
    OUTPUT_DIR / "forensic_disposition_version_profile.csv",
    index=False
)


# ============================================================
# E. AGENT IDENTITY FORENSICS
# ============================================================

print("\n" + "=" * 90)
print("E. AGENT IDENTITY FORENSICS")
print("=" * 90)

agents = datasets["agents"].copy()
sessions = datasets["agent_sessions"].copy()


# E1. Agent identity consistency

agent_identity_profile = (
    agents
    .groupby("agent_id")
    .agg(
        employee_codes=("employee_code", "nunique"),
        names=("agent_name", "nunique"),
        vendors=("vendor_id", "nunique"),
        teams=("team", "nunique"),
        statuses=("status", "nunique")
    )
    .reset_index()
)

agent_identity_flags = agent_identity_profile[
    (
        (agent_identity_profile["employee_codes"] > 1)
        |
        (agent_identity_profile["names"] > 1)
        |
        (agent_identity_profile["vendors"] > 1)
        |
        (agent_identity_profile["teams"] > 1)
    )
].copy()

print(
    "Agent identity flags:",
    len(agent_identity_flags)
)

display(agent_identity_flags)

agent_identity_flags.to_csv(
    OUTPUT_DIR / "forensic_agent_identity_flags.csv",
    index=False
)


# E2. Agent session overlaps

sessions["login_at"] = pd.to_datetime(
    sessions["login_at"],
    errors="coerce"
)

sessions["logout_at"] = pd.to_datetime(
    sessions["logout_at"],
    errors="coerce"
)

session_overlap_flags = []

for agent_id, group in sessions.dropna(
    subset=[
        "agent_id",
        "login_at",
        "logout_at"
    ]
).groupby("agent_id"):

    group = group.sort_values("login_at")

    previous_logout = None
    previous_session = None

    for _, row in group.iterrows():

        if (
            previous_logout is not None
            and row["login_at"] < previous_logout
        ):

            session_overlap_flags.append({
                "agent_id": agent_id,
                "previous_session_id": previous_session,
                "current_session_id": row["session_id"],
                "previous_logout": previous_logout,
                "current_login": row["login_at"]
            })

        if (
            previous_logout is None
            or row["logout_at"] > previous_logout
        ):
            previous_logout = row["logout_at"]
            previous_session = row["session_id"]

session_overlap_df = pd.DataFrame(
    session_overlap_flags
)

print(
    "Agent session overlaps:",
    len(session_overlap_df)
)

display(session_overlap_df.head(50))

session_overlap_df.to_csv(
    OUTPUT_DIR / "forensic_agent_session_overlaps.csv",
    index=False
)


# E3. Calls with unknown agent

agent_ids = set(
    agents["agent_id"].dropna()
)

unknown_call_agents = calls[
    calls["agent_id"].notna()
    &
    ~calls["agent_id"].isin(agent_ids)
].copy()

print(
    "Calls with unknown agent IDs:",
    len(unknown_call_agents)
)

display(unknown_call_agents.head(50))

unknown_call_agents.to_csv(
    OUTPUT_DIR / "forensic_unknown_call_agents.csv",
    index=False
)


# ============================================================
# F. PORTFOLIO MIX FORENSICS
# ============================================================

print("\n" + "=" * 90)
print("F. PORTFOLIO MIX FORENSICS")
print("=" * 90)

accounts["opened_at_parsed"] = pd.to_datetime(
    accounts["opened_at"],
    errors="coerce"
)

accounts["month"] = (
    accounts["opened_at_parsed"]
    .dt.to_period("M")
    .astype(str)
)

portfolio_dimensions = [
    "loan_type",
    "dpd",
    "risk_segment",
    "status",
    "schema_version"
]

portfolio_profiles = []

for column in portfolio_dimensions:

    profile = (
        accounts
        .groupby(
            [
                "month",
                column
            ],
            dropna=False
        )
        .size()
        .reset_index(name="account_count")
    )

    profile["share_of_month"] = (
        profile
        .groupby("month")["account_count"]
        .transform(
            lambda x: x / x.sum()
        )
    )

    profile["dimension"] = column

    portfolio_profiles.append(profile)

portfolio_mix_df = pd.concat(
    portfolio_profiles,
    ignore_index=True
)

display(portfolio_mix_df)

portfolio_mix_df.to_csv(
    OUTPUT_DIR / "forensic_portfolio_mix.csv",
    index=False
)


# ============================================================
# G. DENOMINATOR / TARGETING FORENSICS
# ============================================================

print("\n" + "=" * 90)
print("G. DENOMINATOR / TARGETING FORENSICS")
print("=" * 90)

targeting = datasets["daily_targeting"].copy()

targeting["target_date_parsed"] = pd.to_datetime(
    targeting["target_date"],
    errors="coerce"
)

targeting["month"] = (
    targeting["target_date_parsed"]
    .dt.to_period("M")
    .astype(str)
)


# G1. Target population

target_population = (
    targeting
    .groupby("month")
    .agg(
        targeting_rows=("target_id", "size"),
        unique_targets=("target_id", "nunique"),
        unique_accounts=("account_id", "nunique"),
        unique_campaigns=("campaign_id", "nunique")
    )
    .reset_index()
)

target_population[
    "account_population_change_pct"
] = (
    target_population["unique_accounts"]
    .pct_change() * 100
)

display(target_population)

target_population.to_csv(
    OUTPUT_DIR / "forensic_target_population.csv",
    index=False
)


# G2. Target status

target_status_profile = (
    targeting
    .groupby(
        [
            "month",
            "status"
        ],
        dropna=False
    )
    .size()
    .reset_index(name="target_count")
)

target_status_profile[
    "share_within_month"
] = (
    target_status_profile
    .groupby("month")["target_count"]
    .transform(
        lambda x: x / x.sum()
    )
)

display(target_status_profile)

target_status_profile.to_csv(
    OUTPUT_DIR / "forensic_target_status_profile.csv",
    index=False
)


# G3. Target priority

target_priority_profile = (
    targeting
    .groupby(
        [
            "month",
            "priority"
        ],
        dropna=False
    )
    .size()
    .reset_index(name="target_count")
)

target_priority_profile[
    "share_within_month"
] = (
    target_priority_profile
    .groupby("month")["target_count"]
    .transform(
        lambda x: x / x.sum()
    )
)

display(target_priority_profile)

target_priority_profile.to_csv(
    OUTPUT_DIR / "forensic_target_priority_profile.csv",
    index=False
)


# G4. Account population vs targeted population

account_monthly_population = (
    accounts
    .groupby("month")
    .agg(
        account_population=(
            "account_id",
            "nunique"
        )
    )
    .reset_index()
)

denominator_comparison = (
    account_monthly_population
    .merge(
        target_population[
            [
                "month",
                "unique_accounts",
                "unique_campaigns"
            ]
        ],
        on="month",
        how="outer"
    )
    .sort_values("month")
)

denominator_comparison[
    "targeted_share_of_accounts"
] = (
    denominator_comparison["unique_accounts"]
    /
    denominator_comparison["account_population"]
)

display(denominator_comparison)

denominator_comparison.to_csv(
    OUTPUT_DIR / "forensic_denominator_comparison.csv",
    index=False
)


# ============================================================
# H. FORENSIC SUMMARY
# ============================================================

print("\n" + "=" * 90)
print("FORENSIC INVESTIGATION SUMMARY")
print("=" * 90)

summary = pd.DataFrame([{

    "duplicate_payment_ids":
        len(duplicate_payment_ids),

    "duplicate_payment_references":
        len(duplicate_references),

    "duplicate_payment_event_groups":
        len(payment_event_duplicates),

    "payment_borrower_mismatches":
        len(borrower_mismatch),

    "call_borrower_mismatches":
        len(call_borrower_mismatch),

    "call_account_timezone_differences":
        len(timezone_differences),

    "agent_identity_flags":
        len(agent_identity_flags),

    "agent_session_overlaps":
        len(session_overlap_df),

    "unknown_call_agents":
        len(unknown_call_agents),

    "portfolio_dimensions_reviewed":
        len(portfolio_dimensions),

    "months_in_target_population":
        len(target_population),

    "months_in_denominator_comparison":
        len(denominator_comparison)
}])

display(summary)

summary.to_csv(
    OUTPUT_DIR / "forensic_summary_corrected.csv",
    index=False
)


# ============================================================
# FINAL STATUS
# ============================================================

print("\n" + "=" * 90)
print("ASSIGNMENT FORENSICS COMPLETE")
print("=" * 90)

print(
    "Seven assignment-required forensic areas were investigated."
)

print(
    "Raw source files were NOT modified."
)

print(
    f"Forensic outputs saved to: {OUTPUT_DIR}"
)

print(
    "Findings are evidence for investigation, "
    "not automatic proof of fraud, error, causality, "
    "or manipulation."
)

==========================================================================================
CREDRESOLVE — ASSIGNMENT FORENSIC ANALYSIS
==========================================================================================
Datasets loaded: 18

==========================================================================================
A. DUPLICATE PAYMENT FORENSICS
==========================================================================================
Duplicate payment IDs: 500

,payment_id,occurrences,accounts,borrowers,references,amounts,providers
55,PAYMENT0000056,2,1,1,1,1,1
75,PAYMENT0000076,2,1,1,1,1,1
107,PAYMENT0000108,2,1,1,1,1,1
148,PAYMENT0000149,2,1,1,1,1,1
198,PAYMENT0000199,2,1,1,1,1,1
254,PAYMENT0000255,2,1,1,1,1,1
262,PAYMENT0000263,2,1,1,1,1,1
310,PAYMENT0000311,2,1,1,1,1,1
551,PAYMENT0000552,2,1,1,1,1,1
552,PAYMENT0000553,2,1,1,1,1,1
600,PAYMENT0000601,2,1,1,1,1,1
622,PAYMENT0000623,2,1,1,1,1,1
694,PAYMENT0000695,2,1,1,1,1,1
723,PAYMENT0000724,2,1,1,1,1,1
793,PAYMENT0000794,2,1,1,1,1,1
848,PAYMENT0000849,2,1,1,1,1,1
849,PAYMENT0000850,2,1,1,1,1,1
901,PAYMENT0000902,2,1,1,1,1,1
1075,PAYMENT0001076,2,1,1,1,1,1
1153,PAYMENT0001154,2,1,1,1,1,1
1167,PAYMENT0001168,2,1,1,1,1,1
1196,PAYMENT0001197,2,1,1,1,1,1
1207,PAYMENT0001208,2,1,1,1,1,1
1384,PAYMENT0001385,2,1,1,1,1,1
1389,PAYMENT0001390,2,1,1,1,1,1
1407,PAYMENT0001408,2,1,1,1,1,1
1411,PAYMENT0001412,2,1,1,1,1,1
1419,PAYMENT0001420,2,1,1,1,1,1
1420,PAYMENT0001421,2,1,1,1,1,1
1446,PAYMENT0001447,2,1,1,1,1,1
1503,PAYMENT0001504,2,1,1,1,1,1
1531,PAYMENT0001532,2,1,1,1,1,1
1569,PAYMENT0001570,2,1,1,1,1,1
1613,PAYMENT0001614,2,1,1,1,1,1
1689,PAYMENT0001690,2,1,1,1,1,1
1700,PAYMENT0001701,2,1,1,1,1,1
1726,PAYMENT0001727,2,1,1,1,1,1
1756,PAYMENT0001757,2,1,1,1,1,1
1762,PAYMENT0001763,2,1,1,1,1,1
1828,PAYMENT0001829,2,1,1,1,1,1
1842,PAYMENT0001843,2,1,1,1,1,1
1915,PAYMENT0001916,2,1,1,1,1,1
2063,PAYMENT0002064,2,1,1,1,1,1
2091,PAYMENT0002092,2,1,1,1,1,1
2097,PAYMENT0002098,2,1,1,1,1,1
2130,PAYMENT0002131,2,1,1,1,1,1
2147,PAYMENT0002148,2,1,1,1,1,1
2159,PAYMENT0002160,2,1,1,1,1,1
2197,PAYMENT0002198,2,1,1,1,1,1
2241,PAYMENT0002242,2,1,1,1,1,1

Duplicate payment references: 3745

    payment_reference  occurrences  payment_ids  accounts  amounts  providers
0       TXN0000000009            2            1         1        1          1
5       TXN0000000027            2            2         2        2          2
8       TXN0000000032            3            3         3        3          3
28      TXN0000000113            3            3         3        3          3
35      TXN0000000132            2            2         2        2          2
36      TXN0000000134            2            2         2        2          2
39      TXN0000000154            2            2         2        2          2
50      TXN0000000186            2            2         2        2          2
53      TXN0000000196            2            2         2        2          2
58      TXN0000000212            2            2         2        2          2
71      TXN0000000271            2            2         2        2          2
74      TXN0000000277            2            2         2        2          2
75      TXN0000000280            2            2         2        2          2
84      TXN0000000314            2            1         1        1          1
85      TXN0000000327            2            2         2        2          2
86      TXN0000000329            2            2         2        2          2
90      TXN0000000352            2            2         2        2          2
97      TXN0000000374            2            2         2        2          2
112     TXN0000000428            2            2         2        2          2
115     TXN0000000437            3            3         3        3          3
121     TXN0000000454            2            2         2        2          2
126     TXN0000000466            2            1         1        1          1
127     TXN0000000471            2            2         2        2          2
128     TXN0000000475            2            1         1        1          1
131     TXN0000000480            2            2         2        2          1
132     TXN0000000482            2            2         2        2          2
134     TXN0000000487            2            2         2        2          2
136     TXN0000000491            2            2         2        2          2
141     TXN0000000512            4            3         3        3          3
146     TXN0000000531            2            2         2        2          2
154     TXN0000000562            3            2         2        2          1
158     TXN0000000568            2            2         2        2          1
161     TXN0000000578            2            2         2        2          2
163     TXN0000000584            2            2         2        2          2
167     TXN0000000601            2            2         2        2          2
175     TXN0000000619            3            3         3        3          3
177     TXN0000000629            3            3         3        3          2
178     TXN0000000630            2            2         2        2          2
179     TXN0000000635            2            2         2        2          2
189     TXN0000000667            2            2         2        2          2
201     TXN0000000710            3            2         2        2          2
207     TXN0000000732            2            2         2        2          2
213     TXN0000000744            2            2         2        2          2
224     TXN0000000776            4            3         3        3          3
226     TXN0000000782            2            2         2        2          2
229     TXN0000000791            2            2         2        2          2
230     TXN0000000794            2            2         2        2          2
235     TXN0000000806            2            2         2        2          2
236     TXN0000000808            2            2         2        2          2
254     TXN0000000867            2            2         2        2          2

Same account + amount + timestamp groups: 500

       account_id     amount     event_at_parsed  occurrences
24951  ACC0029925   82923.93 2026-02-14 22:43:03            2
30     ACC0000040   75424.76 2026-01-09 11:53:37            2
43     ACC0000056   81814.00 2026-05-12 22:49:22            2
52     ACC0000070   39313.18 2026-07-31 13:58:14            2
115    ACC0000158   47676.38 2026-08-04 19:13:04            2
134    ACC0000170  128514.05 2026-07-22 17:55:30            2
175    ACC0000224    6088.02 2026-01-05 19:51:25            2
442    ACC0000566   37751.99 2026-06-19 23:24:23            2
496    ACC0000632   90265.20 2026-05-31 17:11:54            2
539    ACC0000678   68996.82 2026-02-05 09:47:11            2
580    ACC0000731  119344.12 2026-07-20 22:12:33            2
582    ACC0000734   25006.68 2026-05-23 11:11:30            2
1000   ACC0001193   61932.17 2026-05-25 21:44:06            2
1042   ACC0001243   49622.29 2026-02-15 14:14:35            2
1050   ACC0001254  139630.85 2026-02-28 16:57:14            2
1060   ACC0001262   78628.80 2026-01-26 07:42:21            2
1093   ACC0001297   17061.06 2026-05-27 20:52:32            2
1100   ACC0001307    5970.90 2026-05-07 18:37:15            2
1150   ACC0001376  113118.86 2026-03-04 13:20:58            2
1304   ACC0001542   91071.29 2026-07-02 08:19:31            2
23092  ACC0027690   49249.84 2026-01-25 19:25:17            2
23114  ACC0027713  114617.88 2026-06-26 02:04:40            2
23156  ACC0027765  102727.85 2026-01-02 10:42:54            2
23253  ACC0027881  134905.53 2026-03-29 09:30:15            2
23285  ACC0027928   43712.91 2026-02-05 17:14:30            2
23358  ACC0028014   41291.16 2026-06-08 03:04:11            2
23359  ACC0028014  110097.77 2026-05-27 02:53:34            2
23397  ACC0028045  138294.48 2026-04-16 00:11:18            2
22814  ACC0027372  138310.56 2026-07-19 10:02:37            2
22823  ACC0027382   20009.41 2026-08-07 13:58:58            2
22857  ACC0027423   44217.52 2026-05-23 19:55:15            2
22963  ACC0027533  104351.29 2026-02-14 12:36:42            2
22975  ACC0027547  132282.46 2026-05-22 03:08:55            2
23005  ACC0027575   68606.87 2026-05-31 21:05:53            2
23057  ACC0027651   14890.44 2026-03-19 18:57:03            2
23091  ACC0027689  106082.57 2026-02-11 12:54:37            2
22633  ACC0027145  119533.70 2026-06-13 23:19:13            2
22685  ACC0027223  128476.91 2026-03-19 03:47:07            2
22704  ACC0027258   31004.80 2026-01-28 05:33:36            2
22708  ACC0027266   37078.02 2026-03-11 22:36:19            2
22741  ACC0027301   36175.31 2026-03-21 17:49:04            2
22749  ACC0027308   92013.22 2026-07-14 18:15:01            2
22774  ACC0027331  143934.05 2026-07-17 08:00:53            2
22786  ACC0027348   49208.88 2026-04-13 09:00:51            2
22228  ACC0026650   45817.54 2026-05-01 05:10:02            2
22288  ACC0026727    9833.11 2026-04-16 07:04:18            2
22357  ACC0026816  100085.00 2026-06-12 21:03:06            2
22379  ACC0026843  105356.38 2026-01-05 16:46:16            2
22415  ACC0026891   34222.77 2026-03-21 02:00:10            2
22538  ACC0027035   79866.31 2026-07-26 08:46:44            2

==========================================================================================
B. ATTRIBUTION FORENSICS
==========================================================================================
Payment borrower/account mismatches: 25113

,payment_id,account_id,borrower_id,event_at,payment_reference,amount,payment_status,payment_method,provider_id,event_at_parsed,account_borrower_id,borrower_mismatch
0,PAYMENT0000001,ACC0015539,BRW0011363,2026-02-27 01:28:12,TXN0000007457,22433.23,FAILED,CARD,VND0000001,2026-02-27 01:28:12,BRW0010501,True
1,PAYMENT0000002,ACC0004445,BRW0011306,2026-07-23 20:25:20,TXN0000030016,23295.11,FAILED,UPI,VND0000004,2026-07-23 20:25:20,BRW0003278,True
2,PAYMENT0000003,ACC0003853,BRW0002549,2026-01-11 21:27:46,TXN0000010466,118814.97,FAILED,NACH,VND0000013,2026-01-11 21:27:46,BRW0007156,True
3,PAYMENT0000004,ACC0017531,BRW0006618,2026-06-16 02:35:21,TXN0000031781,145082.17,REVERSED,CASH,VND0000013,2026-06-16 02:35:21,BRW0001549,True
4,PAYMENT0000005,ACC0001770,BRW0011492,2026-03-03 06:08:23,TXN0000059257,115148.46,SUCCESS,NETBANKING,VND0000013,2026-03-03 06:08:23,BRW0008515,True
5,PAYMENT0000006,ACC0002408,BRW0009136,2026-05-25 10:59:51,TXN0000052202,142468.84,SUCCESS,CARD,VND0000012,2026-05-25 10:59:51,BRW0008668,True
6,PAYMENT0000007,ACC0017147,BRW0004710,2026-05-08 11:45:34,TXN0000050767,79641.72,SUCCESS,NETBANKING,VND0000008,2026-05-08 11:45:34,BRW0006632,True
7,PAYMENT0000008,ACC0027360,BRW0008644,2026-01-16 08:37:42,TXN0000061682,80638.15,SUCCESS,CARD,VND0000009,2026-01-16 08:37:42,BRW0006467,True
8,PAYMENT0000009,ACC0005092,BRW0003019,2026-03-31 08:11:38,TXN0000046720,75028.44,SUCCESS,CASH,VND0000003,2026-03-31 08:11:38,BRW0005156,True
9,PAYMENT0000010,ACC0011343,BRW0010947,2026-07-20 20:51:33,TXN0000031163,80004.84,SUCCESS,UPI,VND0000005,2026-07-20 20:51:33,BRW0002725,True
10,PAYMENT0000011,ACC0022813,BRW0011517,2026-06-13 10:49:29,TXN0000066098,27561.35,SUCCESS,UPI,VND0000010,2026-06-13 10:49:29,BRW0007982,True
11,PAYMENT0000012,ACC0008138,BRW0000540,2026-03-13 17:05:25,TXN0000046491,116971.89,REVERSED,NETBANKING,VND0000001,2026-03-13 17:05:25,BRW0009324,True
12,PAYMENT0000013,ACC0026504,BRW0009822,2026-05-06 22:30:42,NaN,41543.11,SUCCESS,CARD,VND0000013,2026-05-06 22:30:42,BRW0000137,True
13,PAYMENT0000014,ACC0017077,BRW0011703,2026-03-08 16:59:47,TXN0000065948,12762.88,SUCCESS,NETBANKING,VND0000009,2026-03-08 16:59:47,BRW0003882,True
14,PAYMENT0000015,ACC0003730,BRW0000271,2026-01-25 08:23:30,TXN0000012250,15237.53,SUCCESS,CARD,VND0000003,2026-01-25 08:23:30,BRW0003049,True
15,PAYMENT0000016,ACC0005478,BRW0009233,2026-06-30 06:27:32,TXN0000030836,128395.49,SUCCESS,UPI,VND0000015,2026-06-30 06:27:32,BRW0001809,True
16,PAYMENT0000017,ACC0025191,BRW0000862,2026-06-02 12:36:12,TXN0000034871,112272.64,SUCCESS,NETBANKING,VND0000011,2026-06-02 12:36:12,BRW0008426,True
17,PAYMENT0000018,ACC0000379,BRW0002519,2026-06-15 08:11:44,TXN0000063434,18292.79,SUCCESS,NACH,VND0000008,2026-06-15 08:11:44,BRW0002465,True
18,PAYMENT0000019,ACC0028404,BRW0011115,2026-02-19 22:42:24,TXN0000040964,102897.37,SUCCESS,NETBANKING,VND0000015,2026-02-19 22:42:24,BRW0001748,True
19,PAYMENT0000020,ACC0022251,BRW0011071,2026-01-10 19:06:03,TXN0000027006,144661.69,REVERSED,CARD,VND0000003,2026-01-10 19:06:03,BRW0007176,True
20,PAYMENT0000021,ACC0021407,BRW0000136,2026-05-06 06:27:56,TXN0000066590,145099.11,SUCCESS,NACH,VND0000003,2026-05-06 06:27:56,BRW0005938,True
21,PAYMENT0000022,ACC0013552,BRW0009466,2026-07-04 23:55:34,TXN0000057611,46845.47,PENDING,UPI,VND0000010,2026-07-04 23:55:34,BRW0001826,True
22,PAYMENT0000023,ACC0017680,BRW0008221,2026-02-14 05:51:53,TXN0000059767,139033.39,SUCCESS,NACH,VND0000005,2026-02-14 05:51:53,BRW0000385,True
23,PAYMENT0000024,ACC0016623,BRW0004516,2026-01-26 20:49:12,TXN0000068205,7887.61,FAILED,CASH,VND0000005,2026-01-26 20:49:12,BRW0005041,True
24,PAYMENT0000025,ACC0016158,BRW0000293,2026-05-23 15:23:07,TXN0000007142,26782.35,SUCCESS,UPI,VND0000011,2026-05-23 15:23:07,BRW0010812,True
25,PAYMENT0000026,ACC0017181,BRW0005542,2026-02-07 23:29:31,TXN0000067314,6660.28,PENDING,NACH,VND0000013,2026-02-07 23:29:31,BRW0006909,True
26,PAYMENT0000027,ACC0025045,BRW0007439,2026-06-22 11:53:42,TXN0000026155,126430.03,SUCCESS,CARD,VND0000013,2026-06-22 11:53:42,BRW0006935,True
27,PAYMENT0000028,ACC0028651,BRW0011101,2026-05-24 23:43:17,TXN0000028567,74205.30,REVERSED,CARD,VND0000001,2026-05-24 23:43:17,BRW0010844,True
28,PAYMENT0000029,ACC0001438,BRW0009880,2026-07-30 13:56:31,TXN0000028751,119423.32,SUCCESS,UPI,VND0000001,2026-07-30 13:56:31,BRW0009896,True
29,PAYMENT0000030,ACC0002796,BRW0002661,2026-04-07 17:43:51,TXN0000008881,107924.04,SUCCESS,CASH,VND0000008,2026-04-07 17:43:51,BRW0007593,True
30,PAYMENT0000031,ACC0006749,BRW0010349,2026-07-07 16:36:43,TXN0000022660,16764.69,SUCCESS,NETBANKING,VND0000003,2026-07-07 16:36:43,BRW0008648,True
31,PAYMENT0000032,ACC0025921,BRW0005481,2026-02-27 09:24:31,TXN0000033075,1416.01,FAILED,NACH,VND0000003,2026-02-27 09:24:31,BRW0010354,True
32,PAYMENT0000033,ACC0024587,BRW0010151,2026-05-14 07:30:20,TXN0000063530,74516.08,FAILED,CARD,VND0000008,2026-05-14 07:30:20,BRW0011736,True
33,PAYMENT0000034,ACC0024694,BRW0010355,2026-05-31 18:38:13,TXN0000035338,57677.55,SUCCESS,NACH,VND0000002,2026-05-31 18:38:13,BRW0006435,True
34,PAYMENT0000035,ACC0015056,BRW0010024,2026-01-10 12:44:10,TXN0000055836,37838.14,SUCCESS,NACH,VND0000008,2026-01-10 12:44:10,BRW0009188,True
35,PAYMENT0000036,ACC0005478,BRW0006165,2026-06-15 07:01:26,TXN0000001480,78270.05,PENDING,NACH,VND0000004,2026-06-15 07:01:26,BRW0001809,True
36,PAYMENT0000037,ACC0019433,BRW0000459,2026-03-29 07:09:14,TXN0000031615,26255.04,REVERSED,NACH,VND0000002,2026-03-29 07:09:14,BRW0009454,True
37,PAYMENT0000038,ACC0019855,BRW0008279,2026-07-13 08:49:29,TXN0000031736,96614.79,SUCCESS,UPI,VND0000006,2026-07-13 08:49:29,BRW0008976,True
38,PAYMENT0000039,ACC0012581,BRW0000027,2026-06-19 04:58:51,TXN0000049765,21486.61,SUCCESS,NACH,VND0000007,2026-06-19 04:58:51,BRW0005074,True
39,PAYMENT0000040,ACC0010832,BRW0001343,2026-04-16 06:56:09,TXN0000000566,144290.21,SUCCESS,UPI,VND0000005,2026-04-16 06:56:09,BRW0006228,True
40,PAYMENT0000041,ACC0025956,BRW0010110,2026-04-28 22:03:24,TXN0000053937,94558.06,SUCCESS,CARD,VND0000011,2026-04-28 22:03:24,BRW0002657,True
41,PAYMENT0000042,ACC0009797,BRW0009287,2026-06-11 02:06:40,TXN0000027687,18096.51,SUCCESS,NACH,VND0000008,2026-06-11 02:06:40,BRW0005551,True
42,PAYMENT0000043,ACC0014270,BRW0001356,2026-02-22 18:27:14,TXN0000015829,55667.11,FAILED,NACH,VND0000009,2026-02-22 18:27:14,BRW0002003,True
43,PAYMENT0000044,ACC0015075,BRW0007104,2026-06-02 12:02:25,TXN0000034009,24965.91,SUCCESS,NACH,VND0000004,2026-06-02 12:02:25,BRW0007722,True
44,PAYMENT0000045,ACC0019329,BRW0010222,2026-04-06 18:52:28,TXN0000016905,45538.35,SUCCESS,NACH,VND0000013,2026-04-06 18:52:28,BRW0004071,True
45,PAYMENT0000046,ACC0028983,BRW0010609,2026-04-17 06:26:52,TXN0000042379,125117.22,REVERSED,NACH,VND0000015,2026-04-17 06:26:52,BRW0003643,True
46,PAYMENT0000047,ACC0006578,BRW0009321,2026-05-28 09:56:49,TXN0000067037,15939.02,FAILED,CARD,VND0000002,2026-05-28 09:56:49,BRW0005446,True
47,PAYMENT0000048,ACC0002536,BRW0000889,2026-06-17 01:15:38,TXN0000017025,142833.99,SUCCESS,NETBANKING,VND0000002,2026-06-17 01:15:38,BRW0000841,True
48,PAYMENT0000049,ACC0020737,BRW0005627,2026-02-27 16:41:48,TXN0000029967,58541.48,SUCCESS,CARD,VND0000002,2026-02-27 16:41:48,BRW0005244,True
49,PAYMENT0000050,ACC0013852,BRW0001708,2026-08-07 14:12:29,TXN0000044041,57995.58,FAILED,NACH,VND0000014,2026-08-07 14:12:29,BRW0007389,True

Call borrower/account mismatches: 89939

,call_id,account_id,borrower_id,event_at,agent_id,campaign_id,direction,vendor_id,call_status,duration_sec,timezone,event_at_parsed,account_borrower_id,borrower_mismatch
0,CALL0000001,ACC0011505,BRW0007139,2026-07-15 15:36:22,AGT0000955,CMP0000015,OUTBOUND,VND0000013,NO_ANSWER,601,Asia/Dubai,2026-07-15 15:36:22,BRW0004617,True
1,CALL0000002,ACC0002025,BRW0006253,2026-06-10 06:48:27,AGT0000853,CMP0000060,OUTBOUND,VND0000001,ANSWERED,224,Asia/Kolkata,2026-06-10 06:48:27,BRW0000115,True
2,CALL0000003,ACC0013375,BRW0007663,2026-04-07 00:35:35,AGT0000525,CMP0000060,OUTBOUND,VND0000008,FAILED,7,Asia/Dubai,2026-04-07 00:35:35,BRW0011598,True
3,CALL0000004,ACC0021534,BRW0008873,2026-02-12 14:16:57,AGT0000945,CMP0000060,OUTBOUND,VND0000001,VOICEMAIL,896,Asia/Dubai,2026-02-12 14:16:57,BRW0001028,True
4,CALL0000005,ACC0018502,BRW0004996,2026-05-24 15:33:12,AGT0000966,CMP0000053,OUTBOUND,VND0000006,ANSWERED,711,Asia/Kolkata,2026-05-24 15:33:12,BRW0005900,True
5,CALL0000006,ACC0011855,BRW0010726,2026-02-04 11:37:08,AGT0000864,CMP0000082,OUTBOUND,VND0000011,NO_ANSWER,18,Asia/Dubai,2026-02-04 11:37:08,BRW0010971,True
6,CALL0000007,ACC0027278,BRW0005268,2026-02-10 10:59:05,AGT0000524,CMP0000001,OUTBOUND,VND0000009,VOICEMAIL,825,Asia/Kolkata,2026-02-10 10:59:05,BRW0007769,True
7,CALL0000008,ACC0007144,BRW0001246,2026-06-14 23:37:56,AGT0000615,CMP0000115,OUTBOUND,VND0000003,VOICEMAIL,437,Asia/Dubai,2026-06-14 23:37:56,BRW0002816,True
8,CALL0000009,ACC0003902,BRW0010076,2026-03-17 16:24:42,AGT0000585,CMP0000090,OUTBOUND,VND0000012,VOICEMAIL,318,UTC,2026-03-17 16:24:42,BRW0007963,True
9,CALL0000010,ACC0009188,BRW0010503,2026-06-24 04:26:34,AGT0000238,CMP0000092,OUTBOUND,VND0000014,ANSWERED,260,UTC,2026-06-24 04:26:34,BRW0007074,True
10,CALL0000011,ACC0008811,BRW0000960,2026-07-23 14:50:00,AGT0000071,CMP0000098,OUTBOUND,VND0000011,NO_ANSWER,115,Asia/Dubai,2026-07-23 14:50:00,BRW0003340,True
11,CALL0000012,ACC0012258,BRW0003468,2026-02-12 20:40:45,AGT0000014,CMP0000107,INBOUND,VND0000008,BUSY,589,UTC,2026-02-12 20:40:45,BRW0011379,True
12,CALL0000013,ACC0014154,BRW0006698,2026-05-30 17:57:19,AGT0000298,CMP0000074,INBOUND,VND0000012,VOICEMAIL,809,Asia/Dubai,2026-05-30 17:57:19,BRW0011312,True
13,CALL0000014,ACC0007396,BRW0005478,2026-01-10 17:09:15,AGT0000992,CMP0000098,OUTBOUND,VND0000008,VOICEMAIL,536,Asia/Dubai,2026-01-10 17:09:15,BRW0001764,True
14,CALL0000015,ACC0003819,BRW0010032,2026-06-13 22:35:10,AGT0000630,CMP0000028,OUTBOUND,VND0000007,FAILED,782,Asia/Dubai,2026-06-13 22:35:10,BRW0010971,True
15,CALL0000016,ACC0004194,BRW0007276,2026-01-01 10:44:31,AGT0000270,CMP0000078,OUTBOUND,VND0000012,FAILED,479,UTC,2026-01-01 10:44:31,BRW0002562,True
16,CALL0000017,ACC0000324,BRW0009995,2026-01-21 16:48:34,AGT0000198,CMP0000048,OUTBOUND,VND0000009,NO_ANSWER,772,Asia/Dubai,2026-01-21 16:48:34,BRW0002953,True
17,CALL0000018,ACC0000064,BRW0011457,2026-04-28 11:02:01,AGT0000040,CMP0000068,OUTBOUND,VND0000003,FAILED,230,UTC,2026-04-28 11:02:01,BRW0010395,True
18,CALL0000019,ACC0021121,BRW0005251,2026-01-05 08:28:07,AGT0000018,CMP0000033,OUTBOUND,VND0000013,VOICEMAIL,399,Asia/Kolkata,2026-01-05 08:28:07,BRW0008638,True
19,CALL0000020,ACC0017100,BRW0009052,2026-04-26 16:31:37,AGT0000641,CMP0000108,OUTBOUND,VND0000012,BUSY,354,UTC,2026-04-26 16:31:37,BRW0004623,True
20,CALL0000021,ACC0028579,BRW0006503,2026-02-14 04:38:51,AGT0000613,CMP0000009,OUTBOUND,VND0000001,VOICEMAIL,63,Asia/Kolkata,2026-02-14 04:38:51,BRW0003246,True
21,CALL0000022,ACC0009881,BRW0008929,2026-08-05 05:55:16,AGT0000842,CMP0000019,OUTBOUND,VND0000001,VOICEMAIL,289,Asia/Kolkata,2026-08-05 05:55:16,BRW0004786,True
22,CALL0000023,ACC0005656,BRW0006248,2026-07-11 16:42:23,AGT0000862,CMP0000096,OUTBOUND,VND0000007,NO_ANSWER,537,Asia/Kolkata,2026-07-11 16:42:23,BRW0009478,True
23,CALL0000024,ACC0020634,BRW0005033,2026-08-04 17:24:59,AGT0000905,CMP0000076,INBOUND,VND0000005,VOICEMAIL,807,Asia/Dubai,2026-08-04 17:24:59,BRW0007820,True
24,CALL0000025,ACC0004249,BRW0002761,2026-06-19 04:18:04,AGT0000638,CMP0000050,INBOUND,VND0000015,FAILED,519,Asia/Dubai,2026-06-19 04:18:04,BRW0003506,True
25,CALL0000026,ACC0002738,BRW0003702,2026-04-08 22:43:02,AGT0000454,CMP0000104,OUTBOUND,VND0000003,ANSWERED,147,Asia/Dubai,2026-04-08 22:43:02,BRW0003872,True
26,CALL0000027,ACC0002663,BRW0007883,2026-01-18 12:26:51,AGT0000841,CMP0000017,OUTBOUND,VND0000005,BUSY,453,Asia/Kolkata,2026-01-18 12:26:51,BRW0006454,True
27,CALL0000028,ACC0013665,BRW0011459,2026-04-28 20:47:37,AGT0000018,CMP0000006,OUTBOUND,VND0000002,FAILED,659,Asia/Kolkata,2026-04-28 20:47:37,BRW0006012,True
28,CALL0000029,ACC0022130,BRW0011674,2026-03-24 00:14:47,AGT0000865,CMP0000055,OUTBOUND,VND0000015,FAILED,46,Asia/Dubai,2026-03-24 00:14:47,BRW0011092,True
30,CALL0000031,ACC0029780,BRW0004398,2026-02-09 19:57:02,AGT0000316,CMP0000001,OUTBOUND,VND0000010,BUSY,806,UTC,2026-02-09 19:57:02,BRW0007974,True
31,CALL0000032,ACC0010981,BRW0009494,2026-03-29 20:46:57,AGT0000789,CMP0000074,OUTBOUND,VND0000005,FAILED,719,Asia/Kolkata,2026-03-29 20:46:57,BRW0002518,True
32,CALL0000033,ACC0020302,BRW0010171,2026-04-26 20:30:26,AGT0000315,CMP0000046,OUTBOUND,VND0000013,VOICEMAIL,44,Asia/Dubai,2026-04-26 20:30:26,BRW0010959,True
33,CALL0000034,ACC0007010,BRW0004684,2026-01-13 07:21:05,AGT0000489,CMP0000035,OUTBOUND,VND0000014,FAILED,335,Asia/Kolkata,2026-01-13 07:21:05,BRW0009403,True
34,CALL0000035,ACC0024768,BRW0007892,2026-06-12 05:33:37,AGT0000268,CMP0000109,OUTBOUND,VND0000012,ANSWERED,827,Asia/Kolkata,2026-06-12 05:33:37,BRW0010584,True
35,CALL0000036,ACC0025120,BRW0004094,2026-04-23 22:06:26,AGT0000515,CMP0000068,OUTBOUND,VND0000012,BUSY,737,Asia/Kolkata,2026-04-23 22:06:26,BRW0010228,True
36,CALL0000037,ACC0009696,BRW0003238,2026-04-20 01:18:52,AGT0000787,CMP0000010,OUTBOUND,VND0000011,BUSY,47,Asia/Kolkata,2026-04-20 01:18:52,BRW0007795,True
37,CALL0000038,ACC0003044,BRW0009956,2026-01-17 19:04:20,AGT0000059,CMP0000051,INBOUND,VND0000011,VOICEMAIL,487,UTC,2026-01-17 19:04:20,BRW0004104,True
38,CALL0000039,ACC0012935,BRW0008063,2026-04-28 03:56:21,AGT0000613,CMP0000062,OUTBOUND,VND0000008,BUSY,681,Asia/Kolkata,2026-04-28 03:56:21,BRW0000976,True
39,CALL0000040,ACC0018788,BRW0003659,2026-07-09 10:23:27,AGT0000172,CMP0000007,OUTBOUND,VND0000007,VOICEMAIL,299,UTC,2026-07-09 10:23:27,BRW0003203,True
40,CALL0000041,ACC0008263,BRW0001425,2026-01-05 17:53:57,AGT0000108,CMP0000050,OUTBOUND,VND0000005,ANSWERED,298,Asia/Dubai,2026-01-05 17:53:57,BRW0008350,True
41,CALL0000042,ACC0001605,BRW0008707,2026-06-20 19:03:46,AGT0000887,CMP0000055,OUTBOUND,VND0000005,FAILED,467,UTC,2026-06-20 19:03:46,BRW0007884,True
42,CALL0000043,ACC0023026,BRW0000740,2026-03-05 03:21:54,AGT0000081,CMP0000011,OUTBOUND,VND0000002,NO_ANSWER,786,Asia/Dubai,2026-03-05 03:21:54,BRW0009480,True
43,CALL0000044,ACC0008487,BRW0000218,2026-01-01 20:35:27,AGT0000271,CMP0000051,OUTBOUND,VND0000002,NO_ANSWER,353,Asia/Kolkata,2026-01-01 20:35:27,BRW0000571,True
44,CALL0000045,ACC0000606,BRW0009525,2026-02-16 06:10:11,NaN,CMP0000095,OUTBOUND,VND0000002,FAILED,156,Asia/Kolkata,2026-02-16 06:10:11,BRW0005770,True
45,CALL0000046,ACC0008985,BRW0006195,2026-08-02 14:41:22,AGT0000578,CMP0000099,OUTBOUND,VND0000002,VOICEMAIL,263,Asia/Dubai,2026-08-02 14:41:22,BRW0011234,True
46,CALL0000047,ACC0004659,BRW0004843,2026-03-31 09:36:09,AGT0000190,CMP0000014,OUTBOUND,VND0000007,FAILED,55,Asia/Kolkata,2026-03-31 09:36:09,BRW0001055,True
47,CALL0000048,ACC0012134,BRW0005819,2026-02-07 04:04:49,AGT0000446,CMP0000072,OUTBOUND,VND0000004,ANSWERED,882,UTC,2026-02-07 04:04:49,BRW0001537,True
48,CALL0000049,ACC0016678,BRW0005102,2026-05-05 04:32:55,AGT0000144,CMP0000062,OUTBOUND,VND0000001,NO_ANSWER,747,Asia/Kolkata,2026-05-05 04:32:55,BRW0001888,True
49,CALL0000050,ACC0025237,BRW0005568,2026-04-24 23:15:21,AGT0000269,CMP0000020,OUTBOUND,VND0000004,ANSWERED,337,UTC,2026-04-24 23:15:21,BRW0007949,True
50,CALL0000051,ACC0027424,BRW0007657,2026-05-21 03:10:57,AGT0000454,CMP0000031,OUTBOUND,VND0000002,VOICEMAIL,82,Asia/Dubai,2026-05-21 03:10:57,BRW0003674,True

Payment-to-prior-call attribution records: 25500

,payment_id,account_id,event_at_parsed,amount,payment_status,call_id,call_event_at,agent_id,campaign_id,vendor_id,call_status,hours_since_prior_call
0,PAYMENT0008675,ACC0014142,2026-01-01 00:14:40,99867.36,SUCCESS,NaN,NaT,NaN,NaN,NaN,NaN,NaN
1,PAYMENT0008644,ACC0003318,2026-01-01 00:27:39,94128.59,REVERSED,NaN,NaT,NaN,NaN,NaN,NaN,NaN
2,PAYMENT0002693,ACC0014449,2026-01-01 00:41:58,101870.25,SUCCESS,NaN,NaT,NaN,NaN,NaN,NaN,NaN
3,PAYMENT0004607,ACC0018164,2026-01-01 00:44:12,63882.71,FAILED,NaN,NaT,NaN,NaN,NaN,NaN,NaN
4,PAYMENT0000307,ACC0026311,2026-01-01 00:46:12,68439.57,FAILED,NaN,NaT,NaN,NaN,NaN,NaN,NaN
5,PAYMENT0024821,ACC0018361,2026-01-01 00:50:36,87906.80,SUCCESS,NaN,NaT,NaN,NaN,NaN,NaN,NaN
6,PAYMENT0011191,ACC0004322,2026-01-01 01:02:22,94150.20,SUCCESS,NaN,NaT,NaN,NaN,NaN,NaN,NaN
7,PAYMENT0008443,ACC0005569,2026-01-01 01:21:07,81954.29,SUCCESS,NaN,NaT,NaN,NaN,NaN,NaN,NaN
8,PAYMENT0020533,ACC0002164,2026-01-01 01:21:45,74524.80,SUCCESS,NaN,NaT,NaN,NaN,NaN,NaN,NaN
9,PAYMENT0018250,ACC0022477,2026-01-01 01:33:19,23224.76,PENDING,NaN,NaT,NaN,NaN,NaN,NaN,NaN
10,PAYMENT0010455,ACC0002916,2026-01-01 01:42:55,14211.83,SUCCESS,NaN,NaT,NaN,NaN,NaN,NaN,NaN
11,PAYMENT0017955,ACC0016208,2026-01-01 02:12:07,130720.85,SUCCESS,NaN,NaT,NaN,NaN,NaN,NaN,NaN
12,PAYMENT0010896,ACC0007568,2026-01-01 03:18:23,47173.69,PENDING,NaN,NaT,NaN,NaN,NaN,NaN,NaN
13,PAYMENT0019351,ACC0002101,2026-01-01 03:23:35,144785.25,FAILED,NaN,NaT,NaN,NaN,NaN,NaN,NaN
14,PAYMENT0002337,ACC0028378,2026-01-01 03:56:34,33260.86,SUCCESS,NaN,NaT,NaN,NaN,NaN,NaN,NaN
15,PAYMENT0020194,ACC0013024,2026-01-01 03:58:00,112139.21,PENDING,NaN,NaT,NaN,NaN,NaN,NaN,NaN
16,PAYMENT0001673,ACC0020007,2026-01-01 04:01:14,31873.27,PENDING,NaN,NaT,NaN,NaN,NaN,NaN,NaN
17,PAYMENT0013883,ACC0017694,2026-01-01 04:15:47,148923.71,FAILED,NaN,NaT,NaN,NaN,NaN,NaN,NaN
18,PAYMENT0008918,ACC0025342,2026-01-01 04:25:40,129926.36,SUCCESS,NaN,NaT,NaN,NaN,NaN,NaN,NaN
19,PAYMENT0011989,ACC0001265,2026-01-01 04:45:10,130617.76,SUCCESS,NaN,NaT,NaN,NaN,NaN,NaN,NaN
20,PAYMENT0017163,ACC0006017,2026-01-01 04:45:59,44410.74,PENDING,NaN,NaT,NaN,NaN,NaN,NaN,NaN
21,PAYMENT0018768,ACC0022220,2026-01-01 04:55:12,115484.68,SUCCESS,NaN,NaT,NaN,NaN,NaN,NaN,NaN
22,PAYMENT0011789,ACC0024193,2026-01-01 05:06:19,6597.34,SUCCESS,NaN,NaT,NaN,NaN,NaN,NaN,NaN
23,PAYMENT0009550,ACC0009344,2026-01-01 05:11:34,130597.53,FAILED,NaN,NaT,NaN,NaN,NaN,NaN,NaN
24,PAYMENT0007525,ACC0014215,2026-01-01 05:13:47,97172.71,SUCCESS,NaN,NaT,NaN,NaN,NaN,NaN,NaN
25,PAYMENT0022916,ACC0001808,2026-01-01 05:16:02,108795.38,SUCCESS,NaN,NaT,NaN,NaN,NaN,NaN,NaN
26,PAYMENT0009338,ACC0001849,2026-01-01 06:09:44,57465.36,SUCCESS,NaN,NaT,NaN,NaN,NaN,NaN,NaN
27,PAYMENT0012797,ACC0023695,2026-01-01 06:12:13,136829.44,SUCCESS,NaN,NaT,NaN,NaN,NaN,NaN,NaN
28,PAYMENT0020245,ACC0022961,2026-01-01 06:35:40,110026.44,SUCCESS,NaN,NaT,NaN,NaN,NaN,NaN,NaN
29,PAYMENT0024358,ACC0002954,2026-01-01 06:43:43,27166.20,SUCCESS,NaN,NaT,NaN,NaN,NaN,NaN,NaN
30,PAYMENT0018074,ACC0004593,2026-01-01 07:37:16,45768.74,SUCCESS,NaN,NaT,NaN,NaN,NaN,NaN,NaN
31,PAYMENT0020470,ACC0007291,2026-01-01 08:34:35,128160.45,SUCCESS,NaN,NaT,NaN,NaN,NaN,NaN,NaN
32,PAYMENT0011695,ACC0021096,2026-01-01 08:43:33,23268.25,SUCCESS,NaN,NaT,NaN,NaN,NaN,NaN,NaN
33,PAYMENT0013597,ACC0019094,2026-01-01 08:56:15,139732.82,REVERSED,NaN,NaT,NaN,NaN,NaN,NaN,NaN
34,PAYMENT0021251,ACC0008308,2026-01-01 08:57:10,47408.90,SUCCESS,NaN,NaT,NaN,NaN,NaN,NaN,NaN
35,PAYMENT0008926,ACC0024696,2026-01-01 09:40:11,51440.29,SUCCESS,NaN,NaT,NaN,NaN,NaN,NaN,NaN
36,PAYMENT0022563,ACC0029491,2026-01-01 09:43:10,96840.65,SUCCESS,NaN,NaT,NaN,NaN,NaN,NaN,NaN
37,PAYMENT0021285,ACC0000549,2026-01-01 09:48:41,58317.85,PENDING,NaN,NaT,NaN,NaN,NaN,NaN,NaN
38,PAYMENT0020866,ACC0013922,2026-01-01 09:58:12,66690.50,SUCCESS,NaN,NaT,NaN,NaN,NaN,NaN,NaN
39,PAYMENT0012745,ACC0013866,2026-01-01 10:09:52,30216.91,SUCCESS,NaN,NaT,NaN,NaN,NaN,NaN,NaN
40,PAYMENT0000919,ACC0016966,2026-01-01 10:17:36,40006.94,SUCCESS,NaN,NaT,NaN,NaN,NaN,NaN,NaN
41,PAYMENT0017407,ACC0024371,2026-01-01 10:18:19,72862.68,SUCCESS,NaN,NaT,NaN,NaN,NaN,NaN,NaN
42,PAYMENT0004244,ACC0000168,2026-01-01 10:21:57,64084.31,SUCCESS,NaN,NaT,NaN,NaN,NaN,NaN,NaN
43,PAYMENT0003184,ACC0018638,2026-01-01 10:48:43,94524.48,SUCCESS,NaN,NaT,NaN,NaN,NaN,NaN,NaN
44,PAYMENT0019759,ACC0020024,2026-01-01 10:51:33,3041.68,FAILED,NaN,NaT,NaN,NaN,NaN,NaN,NaN
45,PAYMENT0009789,ACC0017555,2026-01-01 10:52:26,74979.91,SUCCESS,NaN,NaT,NaN,NaN,NaN,NaN,NaN
46,PAYMENT0019645,ACC0022917,2026-01-01 11:05:56,32723.19,SUCCESS,NaN,NaT,NaN,NaN,NaN,NaN,NaN
47,PAYMENT0021695,ACC0019939,2026-01-01 11:16:07,121327.54,PENDING,NaN,NaT,NaN,NaN,NaN,NaN,NaN
48,PAYMENT0016471,ACC0020018,2026-01-01 11:34:57,3351.45,SUCCESS,NaN,NaT,NaN,NaN,NaN,NaN,NaN
49,PAYMENT0002690,ACC0021732,2026-01-01 11:39:38,100979.96,SUCCESS,NaN,NaT,NaN,NaN,NaN,NaN,NaN

==========================================================================================
C. TIMEZONE FORENSICS
==========================================================================================

       timezone  records           dataset
0  Asia/Kolkata    30485             calls
1    Asia/Dubai    30464             calls
2           UTC    30401             calls
3           UTC    10096          accounts
4  Asia/Kolkata     9981          accounts
5    Asia/Dubai     9923          accounts
6  Asia/Kolkata     7506    agent_sessions
7           UTC     7494    agent_sessions
8           UTC        8  vendor_telephony
9  Asia/Kolkata        7  vendor_telephony

Call/account timezone differences: 60887

,call_id,account_id,borrower_id,event_at,agent_id,campaign_id,direction,vendor_id,call_status,duration_sec,timezone,event_at_parsed,account_timezone,account_timezone_difference_flag
0,CALL0000001,ACC0011505,BRW0007139,2026-07-15 15:36:22,AGT0000955,CMP0000015,OUTBOUND,VND0000013,NO_ANSWER,601,Asia/Dubai,2026-07-15 15:36:22,UTC,True
1,CALL0000002,ACC0002025,BRW0006253,2026-06-10 06:48:27,AGT0000853,CMP0000060,OUTBOUND,VND0000001,ANSWERED,224,Asia/Kolkata,2026-06-10 06:48:27,UTC,True
3,CALL0000004,ACC0021534,BRW0008873,2026-02-12 14:16:57,AGT0000945,CMP0000060,OUTBOUND,VND0000001,VOICEMAIL,896,Asia/Dubai,2026-02-12 14:16:57,UTC,True
4,CALL0000005,ACC0018502,BRW0004996,2026-05-24 15:33:12,AGT0000966,CMP0000053,OUTBOUND,VND0000006,ANSWERED,711,Asia/Kolkata,2026-05-24 15:33:12,UTC,True
5,CALL0000006,ACC0011855,BRW0010726,2026-02-04 11:37:08,AGT0000864,CMP0000082,OUTBOUND,VND0000011,NO_ANSWER,18,Asia/Dubai,2026-02-04 11:37:08,UTC,True
7,CALL0000008,ACC0007144,BRW0001246,2026-06-14 23:37:56,AGT0000615,CMP0000115,OUTBOUND,VND0000003,VOICEMAIL,437,Asia/Dubai,2026-06-14 23:37:56,Asia/Kolkata,True
8,CALL0000009,ACC0003902,BRW0010076,2026-03-17 16:24:42,AGT0000585,CMP0000090,OUTBOUND,VND0000012,VOICEMAIL,318,UTC,2026-03-17 16:24:42,Asia/Kolkata,True
9,CALL0000010,ACC0009188,BRW0010503,2026-06-24 04:26:34,AGT0000238,CMP0000092,OUTBOUND,VND0000014,ANSWERED,260,UTC,2026-06-24 04:26:34,Asia/Kolkata,True
10,CALL0000011,ACC0008811,BRW0000960,2026-07-23 14:50:00,AGT0000071,CMP0000098,OUTBOUND,VND0000011,NO_ANSWER,115,Asia/Dubai,2026-07-23 14:50:00,Asia/Kolkata,True
11,CALL0000012,ACC0012258,BRW0003468,2026-02-12 20:40:45,AGT0000014,CMP0000107,INBOUND,VND0000008,BUSY,589,UTC,2026-02-12 20:40:45,Asia/Dubai,True
12,CALL0000013,ACC0014154,BRW0006698,2026-05-30 17:57:19,AGT0000298,CMP0000074,INBOUND,VND0000012,VOICEMAIL,809,Asia/Dubai,2026-05-30 17:57:19,Asia/Kolkata,True
13,CALL0000014,ACC0007396,BRW0005478,2026-01-10 17:09:15,AGT0000992,CMP0000098,OUTBOUND,VND0000008,VOICEMAIL,536,Asia/Dubai,2026-01-10 17:09:15,UTC,True
14,CALL0000015,ACC0003819,BRW0010032,2026-06-13 22:35:10,AGT0000630,CMP0000028,OUTBOUND,VND0000007,FAILED,782,Asia/Dubai,2026-06-13 22:35:10,UTC,True
16,CALL0000017,ACC0000324,BRW0009995,2026-01-21 16:48:34,AGT0000198,CMP0000048,OUTBOUND,VND0000009,NO_ANSWER,772,Asia/Dubai,2026-01-21 16:48:34,Asia/Kolkata,True
17,CALL0000018,ACC0000064,BRW0011457,2026-04-28 11:02:01,AGT0000040,CMP0000068,OUTBOUND,VND0000003,FAILED,230,UTC,2026-04-28 11:02:01,Asia/Kolkata,True
20,CALL0000021,ACC0028579,BRW0006503,2026-02-14 04:38:51,AGT0000613,CMP0000009,OUTBOUND,VND0000001,VOICEMAIL,63,Asia/Kolkata,2026-02-14 04:38:51,Asia/Dubai,True
21,CALL0000022,ACC0009881,BRW0008929,2026-08-05 05:55:16,AGT0000842,CMP0000019,OUTBOUND,VND0000001,VOICEMAIL,289,Asia/Kolkata,2026-08-05 05:55:16,Asia/Dubai,True
22,CALL0000023,ACC0005656,BRW0006248,2026-07-11 16:42:23,AGT0000862,CMP0000096,OUTBOUND,VND0000007,NO_ANSWER,537,Asia/Kolkata,2026-07-11 16:42:23,UTC,True
24,CALL0000025,ACC0004249,BRW0002761,2026-06-19 04:18:04,AGT0000638,CMP0000050,INBOUND,VND0000015,FAILED,519,Asia/Dubai,2026-06-19 04:18:04,UTC,True
26,CALL0000027,ACC0002663,BRW0007883,2026-01-18 12:26:51,AGT0000841,CMP0000017,OUTBOUND,VND0000005,BUSY,453,Asia/Kolkata,2026-01-18 12:26:51,Asia/Dubai,True
28,CALL0000029,ACC0022130,BRW0011674,2026-03-24 00:14:47,AGT0000865,CMP0000055,OUTBOUND,VND0000015,FAILED,46,Asia/Dubai,2026-03-24 00:14:47,UTC,True
29,CALL0000030,ACC0015282,BRW0007845,2026-06-18 19:24:12,AGT0000850,CMP0000089,OUTBOUND,VND0000008,FAILED,749,UTC,2026-06-18 19:24:12,Asia/Kolkata,True
31,CALL0000032,ACC0010981,BRW0009494,2026-03-29 20:46:57,AGT0000789,CMP0000074,OUTBOUND,VND0000005,FAILED,719,Asia/Kolkata,2026-03-29 20:46:57,Asia/Dubai,True
32,CALL0000033,ACC0020302,BRW0010171,2026-04-26 20:30:26,AGT0000315,CMP0000046,OUTBOUND,VND0000013,VOICEMAIL,44,Asia/Dubai,2026-04-26 20:30:26,UTC,True
33,CALL0000034,ACC0007010,BRW0004684,2026-01-13 07:21:05,AGT0000489,CMP0000035,OUTBOUND,VND0000014,FAILED,335,Asia/Kolkata,2026-01-13 07:21:05,UTC,True
34,CALL0000035,ACC0024768,BRW0007892,2026-06-12 05:33:37,AGT0000268,CMP0000109,OUTBOUND,VND0000012,ANSWERED,827,Asia/Kolkata,2026-06-12 05:33:37,UTC,True
36,CALL0000037,ACC0009696,BRW0003238,2026-04-20 01:18:52,AGT0000787,CMP0000010,OUTBOUND,VND0000011,BUSY,47,Asia/Kolkata,2026-04-20 01:18:52,Asia/Dubai,True
38,CALL0000039,ACC0012935,BRW0008063,2026-04-28 03:56:21,AGT0000613,CMP0000062,OUTBOUND,VND0000008,BUSY,681,Asia/Kolkata,2026-04-28 03:56:21,Asia/Dubai,True
39,CALL0000040,ACC0018788,BRW0003659,2026-07-09 10:23:27,AGT0000172,CMP0000007,OUTBOUND,VND0000007,VOICEMAIL,299,UTC,2026-07-09 10:23:27,Asia/Kolkata,True
40,CALL0000041,ACC0008263,BRW0001425,2026-01-05 17:53:57,AGT0000108,CMP0000050,OUTBOUND,VND0000005,ANSWERED,298,Asia/Dubai,2026-01-05 17:53:57,UTC,True
41,CALL0000042,ACC0001605,BRW0008707,2026-06-20 19:03:46,AGT0000887,CMP0000055,OUTBOUND,VND0000005,FAILED,467,UTC,2026-06-20 19:03:46,Asia/Dubai,True
45,CALL0000046,ACC0008985,BRW0006195,2026-08-02 14:41:22,AGT0000578,CMP0000099,OUTBOUND,VND0000002,VOICEMAIL,263,Asia/Dubai,2026-08-02 14:41:22,Asia/Kolkata,True
46,CALL0000047,ACC0004659,BRW0004843,2026-03-31 09:36:09,AGT0000190,CMP0000014,OUTBOUND,VND0000007,FAILED,55,Asia/Kolkata,2026-03-31 09:36:09,UTC,True
47,CALL0000048,ACC0012134,BRW0005819,2026-02-07 04:04:49,AGT0000446,CMP0000072,OUTBOUND,VND0000004,ANSWERED,882,UTC,2026-02-07 04:04:49,Asia/Kolkata,True
51,CALL0000052,ACC0001834,BRW0007564,2026-04-07 14:27:38,AGT0000360,CMP0000020,OUTBOUND,VND0000012,NO_ANSWER,706,Asia/Kolkata,2026-04-07 14:27:38,Asia/Dubai,True
53,CALL0000054,ACC0029981,BRW0008565,2026-07-08 17:08:17,AGT0000755,CMP0000114,OUTBOUND,VND0000001,FAILED,582,Asia/Dubai,2026-07-08 17:08:17,Asia/Kolkata,True
56,CALL0000057,ACC0016026,BRW0007818,2026-04-11 19:47:42,AGT0000745,CMP0000074,INBOUND,VND0000009,NO_ANSWER,154,Asia/Dubai,2026-04-11 19:47:42,UTC,True
57,CALL0000058,ACC0019088,BRW0002874,2026-03-25 11:39:26,AGT0000127,CMP0000116,OUTBOUND,VND0000008,ANSWERED,867,UTC,2026-03-25 11:39:26,Asia/Dubai,True
58,CALL0000059,ACC0004837,BRW0001292,2026-08-06 11:12:55,AGT0000536,CMP0000111,INBOUND,VND0000007,FAILED,597,UTC,2026-08-06 11:12:55,Asia/Dubai,True
59,CALL0000060,ACC0023992,BRW0011158,2026-01-02 05:37:04,AGT0000942,CMP0000002,OUTBOUND,VND0000015,VOICEMAIL,416,UTC,2026-01-02 05:37:04,Asia/Dubai,True
60,CALL0000061,ACC0021451,BRW0005090,2026-03-19 23:25:59,AGT0000592,CMP0000076,OUTBOUND,VND0000015,VOICEMAIL,470,UTC,2026-03-19 23:25:59,Asia/Dubai,True
61,CALL0000062,ACC0011818,BRW0006455,2026-05-07 16:03:49,AGT0000539,CMP0000091,OUTBOUND,VND0000006,BUSY,131,Asia/Kolkata,2026-05-07 16:03:49,UTC,True
62,CALL0000063,ACC0014378,BRW0000898,2026-04-16 05:42:32,AGT0000121,CMP0000086,OUTBOUND,VND0000013,FAILED,221,Asia/Kolkata,2026-04-16 05:42:32,UTC,True
63,CALL0000064,ACC0022018,BRW0010734,2026-07-27 19:51:14,AGT0000325,CMP0000068,OUTBOUND,VND0000014,BUSY,841,Asia/Kolkata,2026-07-27 19:51:14,Asia/Dubai,True
64,CALL0000065,ACC0022731,BRW0003424,2026-04-11 10:42:48,AGT0000409,CMP0000052,OUTBOUND,VND0000011,ANSWERED,135,UTC,2026-04-11 10:42:48,Asia/Dubai,True
65,CALL0000066,ACC0017255,BRW0001633,2026-06-23 10:00:47,AGT0000350,CMP0000102,INBOUND,VND0000004,VOICEMAIL,374,Asia/Kolkata,2026-06-23 10:00:47,UTC,True
66,CALL0000067,ACC0001545,BRW0010088,2026-04-12 02:24:40,AGT0000495,CMP0000058,OUTBOUND,VND0000007,ANSWERED,153,UTC,2026-04-12 02:24:40,Asia/Dubai,True
67,CALL0000068,ACC0009096,BRW0004811,2026-05-30 09:33:56,AGT0000022,CMP0000056,OUTBOUND,VND0000011,ANSWERED,76,Asia/Kolkata,2026-05-30 09:33:56,UTC,True
68,CALL0000069,ACC0026901,BRW0006326,2026-06-25 12:47:19,AGT0000209,CMP0000092,OUTBOUND,VND0000002,VOICEMAIL,590,UTC,2026-06-25 12:47:19,Asia/Kolkata,True
69,CALL0000070,ACC0013337,BRW0002556,2026-04-07 17:35:41,AGT0000730,CMP0000061,OUTBOUND,VND0000006,VOICEMAIL,304,UTC,2026-04-07 17:35:41,Asia/Kolkata,True

    hour  call_count
0      0        3688
1      1        3799
2      2        3942
3      3        3831
4      4        3751
5      5        3864
6      6        3871
7      7        3850
8      8        3765
9      9        3751
10    10        3854
11    11        3891
12    12        3716
13    13        3871
14    14        3767
15    15        3685
16    16        3903
17    17        3683
18    18        3844
19    19        3841
20    20        3740
21    21        3767
22    22        3727
23    23        3949

==========================================================================================
D. VENDOR MAPPING / VERSION FORENSICS
==========================================================================================

,vendor_id,vendor_name,vendor_account_id,timezone,status,schema_version
0,VND0000001,Airtel,VAC342762,Asia/Kolkata,INACTIVE,v3
1,VND0000002,Exotel,VAC456766,UTC,INACTIVE,v3
2,VND0000003,Twilio,VAC074211,UTC,INACTIVE,v3
3,VND0000004,Twilio,VAC321507,UTC,ACTIVE,v1
4,VND0000005,Twilio,VAC976733,Asia/Kolkata,ACTIVE,v1
5,VND0000006,Knowlarity,VAC544470,UTC,ACTIVE,v2
6,VND0000007,TataTele,VAC997592,UTC,INACTIVE,v1
7,VND0000008,Airtel,VAC496672,Asia/Kolkata,INACTIVE,v3
8,VND0000009,Exotel,VAC382568,Asia/Kolkata,INACTIVE,v1
9,VND0000010,Airtel,VAC172916,UTC,INACTIVE,v1
10,VND0000011,Airtel,VAC461665,UTC,ACTIVE,v3
11,VND0000012,Airtel,VAC583104,UTC,INACTIVE,v1
12,VND0000013,Knowlarity,VAC138790,Asia/Kolkata,ACTIVE,v1
13,VND0000014,Knowlarity,VAC547425,Asia/Kolkata,INACTIVE,v3
14,VND0000015,TataTele,VAC225367,Asia/Kolkata,ACTIVE,v2

       month   vendor_id schema_version  call_count
0    2025-12  VND0000013             v1           1
1    2026-01  VND0000001             v3         889
2    2026-01  VND0000002             v3         829
3    2026-01  VND0000003             v3         885
4    2026-01  VND0000004             v1         860
..       ...         ...            ...         ...
116  2026-08  VND0000011             v3         233
117  2026-08  VND0000012             v1         203
118  2026-08  VND0000013             v1         211
119  2026-08  VND0000014             v3         231
120  2026-08  VND0000015             v2         201

[121 rows x 4 columns]

       month disposition_version disposition_code  records
0    2026-01              legacy         CALLBACK      194
1    2026-01              legacy          DISPUTE      181
2    2026-01              legacy       NO_CONTACT      198
3    2026-01              legacy             PAID      167
4    2026-01              legacy   PROMISE_TO_PAY      203
..       ...                 ...              ...      ...
211  2026-08                  v2   PROMISE_TO_PAY       42
212  2026-08                  v2              PTP       40
213  2026-08                  v2       PTP_BROKEN       52
214  2026-08                  v2          REFUSED       36
215  2026-08                  v2     WRONG_NUMBER       39

[216 rows x 4 columns]

==========================================================================================
E. AGENT IDENTITY FORENSICS
==========================================================================================
Agent identity flags: 1000

       agent_id  employee_codes  names  vendors  teams  statuses
0    AGT0000001              23     10       10      5         3
1    AGT0000002              23     10       12      5         3
2    AGT0000003              28     10       12      5         3
3    AGT0000004              28     10       12      5         3
4    AGT0000005              29     10       15      5         3
..          ...             ...    ...      ...    ...       ...
995  AGT0000996              26     10       12      5         3
996  AGT0000997              40     10       15      5         3
997  AGT0000998              32     10       13      5         3
998  AGT0000999              27      8       11      5         3
999  AGT0001000              30      9       13      5         3

[1000 rows x 6 columns]

Agent session overlaps: 215

,agent_id,previous_session_id,current_session_id,previous_logout,current_login
0,AGT0000001,SES0001253,SES0005430,2026-05-31 13:39:23,2026-05-31 08:05:01
1,AGT0000012,SES0014890,SES0002887,2026-08-08 23:10:35,2026-08-08 14:14:23
2,AGT0000014,SES0007862,SES0012933,2026-06-29 14:11:58,2026-06-29 13:11:30
3,AGT0000015,SES0002219,SES0004594,2026-04-04 17:09:38,2026-04-04 09:26:21
4,AGT0000022,SES0002186,SES0002562,2026-07-01 17:07:28,2026-07-01 16:33:22
5,AGT0000025,SES0001931,SES0000081,2026-03-28 01:21:04,2026-03-27 22:28:51
6,AGT0000029,SES0009081,SES0009177,2026-01-08 01:37:51,2026-01-08 01:02:48
7,AGT0000035,SES0013613,SES0009538,2026-03-25 13:08:39,2026-03-25 03:19:14
8,AGT0000043,SES0009271,SES0005290,2026-06-24 07:45:35,2026-06-24 03:08:46
9,AGT0000050,SES0008532,SES0005177,2026-01-11 09:17:56,2026-01-11 02:56:06
10,AGT0000050,SES0007663,SES0009737,2026-07-27 10:32:23,2026-07-27 10:01:22
11,AGT0000055,SES0002911,SES0013890,2026-02-18 14:51:12,2026-02-18 12:25:51
12,AGT0000056,SES0013134,SES0013066,2026-06-06 04:22:59,2026-06-06 03:51:39
13,AGT0000059,SES0005052,SES0010208,2026-05-20 14:37:50,2026-05-20 10:34:33
14,AGT0000069,SES0001663,SES0012204,2026-04-30 10:49:37,2026-04-30 06:21:32
15,AGT0000077,SES0002151,SES0005725,2026-01-29 17:49:34,2026-01-29 15:05:20
16,AGT0000086,SES0014644,SES0014392,2026-07-15 11:45:10,2026-07-15 11:42:56
17,AGT0000086,SES0014392,SES0001747,2026-07-15 14:42:34,2026-07-15 13:26:39
18,AGT0000097,SES0004911,SES0010182,2026-02-23 01:50:35,2026-02-22 23:15:47
19,AGT0000103,SES0014320,SES0001010,2026-05-31 18:09:37,2026-05-31 14:15:31
20,AGT0000118,SES0013840,SES0005942,2026-03-07 20:35:58,2026-03-07 20:10:33
21,AGT0000127,SES0004752,SES0006060,2026-07-31 00:51:47,2026-07-30 21:43:15
22,AGT0000146,SES0011764,SES0006863,2026-06-02 04:08:56,2026-06-01 21:47:21
23,AGT0000156,SES0001018,SES0010336,2026-01-16 08:10:02,2026-01-16 02:41:41
24,AGT0000159,SES0001605,SES0005404,2026-05-19 06:18:42,2026-05-19 00:59:37
25,AGT0000168,SES0003525,SES0002977,2026-06-07 00:33:16,2026-06-06 23:01:45
26,AGT0000171,SES0014282,SES0009437,2026-06-19 14:21:14,2026-06-19 05:34:44
27,AGT0000173,SES0009887,SES0006648,2026-02-16 23:51:57,2026-02-16 22:27:41
28,AGT0000173,SES0006265,SES0011570,2026-03-20 13:02:28,2026-03-20 09:17:43
29,AGT0000175,SES0010147,SES0003702,2026-01-05 07:20:18,2026-01-04 21:24:13
30,AGT0000177,SES0003695,SES0001546,2026-02-03 00:07:27,2026-02-02 22:42:11
31,AGT0000182,SES0006732,SES0003127,2026-01-21 19:53:00,2026-01-21 15:34:06
32,AGT0000184,SES0013436,SES0009842,2026-05-26 17:14:28,2026-05-26 15:43:07
33,AGT0000185,SES0009394,SES0000046,2026-03-30 21:56:56,2026-03-30 13:15:47
34,AGT0000189,SES0014436,SES0003494,2026-03-21 06:43:08,2026-03-21 03:34:40
35,AGT0000193,SES0013944,SES0011853,2026-06-23 01:38:41,2026-06-22 16:51:13
36,AGT0000209,SES0003016,SES0005743,2026-01-29 18:59:11,2026-01-29 11:14:39
37,AGT0000214,SES0003617,SES0010525,2026-01-28 18:38:11,2026-01-28 11:42:57
38,AGT0000215,SES0004311,SES0012829,2026-05-21 17:19:44,2026-05-21 13:29:55
39,AGT0000218,SES0014132,SES0001161,2026-05-18 17:15:56,2026-05-18 09:49:48
40,AGT0000225,SES0003295,SES0004021,2026-06-28 02:01:16,2026-06-28 01:22:37
41,AGT0000227,SES0010313,SES0014974,2026-06-14 16:12:04,2026-06-14 08:30:01
42,AGT0000229,SES0001687,SES0001664,2026-04-21 23:44:26,2026-04-21 15:13:02
43,AGT0000231,SES0005255,SES0006616,2026-03-24 16:09:07,2026-03-24 07:16:22
44,AGT0000237,SES0001201,SES0014868,2026-01-05 17:36:01,2026-01-05 10:45:26
45,AGT0000243,SES0001880,SES0004794,2026-01-25 20:42:59,2026-01-25 19:51:51
46,AGT0000251,SES0009186,SES0008115,2026-04-18 04:01:38,2026-04-18 02:58:42
47,AGT0000253,SES0010405,SES0013933,2026-03-12 11:03:23,2026-03-12 09:58:30
48,AGT0000256,SES0000774,SES0004207,2026-07-05 03:46:17,2026-07-05 02:38:31
49,AGT0000257,SES0012939,SES0004442,2026-02-19 13:12:14,2026-02-19 08:39:52

Calls with unknown agent IDs: 0

Empty DataFrame
Columns: [call_id, account_id, borrower_id, event_at, agent_id, campaign_id, direction, vendor_id, call_status, duration_sec, timezone, event_at_parsed]
Index: []

==========================================================================================
F. PORTFOLIO MIX FORENSICS
==========================================================================================

,month,loan_type,account_count,share_of_month,dimension,dpd,risk_segment,status,schema_version
0,2024-01,AUTO,270,0.205950,loan_type,NaN,NaN,NaN,NaN
1,2024-01,BNPL,250,0.190694,loan_type,NaN,NaN,NaN,NaN
2,2024-01,CONSUMER,264,0.201373,loan_type,NaN,NaN,NaN,NaN
3,2024-01,CREDIT_CARD,262,0.199847,loan_type,NaN,NaN,NaN,NaN
4,2024-01,PERSONAL,265,0.202136,loan_type,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
616,2025-10,NaN,447,0.337358,schema_version,NaN,NaN,NaN,v2
617,2025-10,NaN,429,0.323774,schema_version,NaN,NaN,NaN,v3
618,2025-11,NaN,406,0.323764,schema_version,NaN,NaN,NaN,v1
619,2025-11,NaN,403,0.321372,schema_version,NaN,NaN,NaN,v2
620,2025-11,NaN,445,0.354864,schema_version,NaN,NaN,NaN,v3

==========================================================================================
G. DENOMINATOR / TARGETING FORENSICS
==========================================================================================

,month,targeting_rows,unique_targets,unique_accounts,unique_campaigns,account_population_change_pct
0,2026-01,6369,6369,5732,120,NaN
1,2026-02,5709,5709,5160,120,-9.979065
2,2026-03,6290,6290,5666,120,9.806202
3,2026-04,6205,6205,5585,120,-1.429580
4,2026-05,6442,6442,5800,120,3.849597
5,2026-06,6154,6154,5535,120,-4.568966
6,2026-07,6230,6230,5666,120,2.366757
7,2026-08,1601,1601,1566,120,-72.361454

      month     status  target_count  share_within_month
0   2026-01  CONTACTED          1562            0.245250
1   2026-01    EXPIRED          1615            0.253572
2   2026-01     QUEUED          1553            0.243837
3   2026-01    SKIPPED          1639            0.257340
4   2026-02  CONTACTED          1409            0.246803
5   2026-02    EXPIRED          1473            0.258014
6   2026-02     QUEUED          1454            0.254686
7   2026-02    SKIPPED          1373            0.240497
8   2026-03  CONTACTED          1564            0.248649
9   2026-03    EXPIRED          1590            0.252782
10  2026-03     QUEUED          1609            0.255803
11  2026-03    SKIPPED          1527            0.242766
12  2026-04  CONTACTED          1577            0.254150
13  2026-04    EXPIRED          1560            0.251410
14  2026-04     QUEUED          1515            0.244158
15  2026-04    SKIPPED          1553            0.250282
16  2026-05  CONTACTED          1617            0.251009
17  2026-05    EXPIRED          1597            0.247904
18  2026-05     QUEUED          1605            0.249146
19  2026-05    SKIPPED          1623            0.251940
20  2026-06  CONTACTED          1547            0.251381
21  2026-06    EXPIRED          1594            0.259019
22  2026-06     QUEUED          1477            0.240006
23  2026-06    SKIPPED          1536            0.249594
24  2026-07  CONTACTED          1571            0.252167
25  2026-07    EXPIRED          1537            0.246709
26  2026-07     QUEUED          1589            0.255056
27  2026-07    SKIPPED          1533            0.246067
28  2026-08  CONTACTED           407            0.254216
29  2026-08    EXPIRED           405            0.252967
30  2026-08     QUEUED           400            0.249844
31  2026-08    SKIPPED           389            0.242973

      month  priority  target_count  share_within_month
0   2026-01         1           614            0.096404
1   2026-01         2           644            0.101115
2   2026-01         3           636            0.099859
3   2026-01         4           639            0.100330
4   2026-01         5           608            0.095462
..      ...       ...           ...                 ...
75  2026-08         6           141            0.088070
76  2026-08         7           151            0.094316
77  2026-08         8           188            0.117427
78  2026-08         9           163            0.101811
79  2026-08        10           137            0.085572

[80 rows x 4 columns]

,month,account_population,unique_accounts,unique_campaigns,targeted_share_of_accounts
0,2024-01,1311.0,NaN,NaN,NaN
1,2024-02,1299.0,NaN,NaN,NaN
2,2024-03,1404.0,NaN,NaN,NaN
3,2024-04,1263.0,NaN,NaN,NaN
4,2024-05,1287.0,NaN,NaN,NaN
5,2024-06,1219.0,NaN,NaN,NaN
6,2024-07,1324.0,NaN,NaN,NaN
7,2024-08,1358.0,NaN,NaN,NaN
8,2024-09,1326.0,NaN,NaN,NaN
9,2024-10,1362.0,NaN,NaN,NaN
10,2024-11,1288.0,NaN,NaN,NaN
11,2024-12,1306.0,NaN,NaN,NaN
12,2025-01,1332.0,NaN,NaN,NaN
13,2025-02,1232.0,NaN,NaN,NaN
14,2025-03,1355.0,NaN,NaN,NaN
15,2025-04,1258.0,NaN,NaN,NaN
16,2025-05,1273.0,NaN,NaN,NaN
17,2025-06,1256.0,NaN,NaN,NaN
18,2025-07,1284.0,NaN,NaN,NaN
19,2025-08,1323.0,NaN,NaN,NaN
20,2025-09,1361.0,NaN,NaN,NaN
21,2025-10,1325.0,NaN,NaN,NaN
22,2025-11,1254.0,NaN,NaN,NaN
23,2026-01,NaN,5732.0,120.0,NaN
24,2026-02,NaN,5160.0,120.0,NaN
25,2026-03,NaN,5666.0,120.0,NaN
26,2026-04,NaN,5585.0,120.0,NaN
27,2026-05,NaN,5800.0,120.0,NaN
28,2026-06,NaN,5535.0,120.0,NaN
29,2026-07,NaN,5666.0,120.0,NaN
30,2026-08,NaN,1566.0,120.0,NaN

==========================================================================================
FORENSIC INVESTIGATION SUMMARY
==========================================================================================

,duplicate_payment_ids,duplicate_payment_references,duplicate_payment_event_groups,payment_borrower_mismatches,call_borrower_mismatches,call_account_timezone_differences,agent_identity_flags,agent_session_overlaps,unknown_call_agents,portfolio_dimensions_reviewed,months_in_target_population,months_in_denominator_comparison
0,500,3745,500,25113,89939,60887,1000,215,0,5,8,31

==========================================================================================
ASSIGNMENT FORENSICS COMPLETE
==========================================================================================
Seven assignment-required forensic areas were investigated.
Raw source files were NOT modified.
Forensic outputs saved to: c:\Users\DELL\Documents\CredResolve Collections Recovery Analytics\outputs\tables
Findings are evidence for investigation, not automatic proof of fraud, error, causality, or manipulation.